import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
const ChatSummary = ({ summary, onSummarize }) => {
    const [expanded, setExpanded] = useState(true);
    const toggleExpand = () => {
        setExpanded(!expanded);
    };
    return (_jsxs("div", { className: "bg-white rounded p-2 mb-2", children: [_jsx("div", { className: "flex justify-between items-center mb-2", children: _jsxs("div", { className: "flex items-center", children: [_jsx("div", { className: "w-5 h-5 flex items-center justify-center border border-gray-300 rounded mr-2", children: _jsx("span", { className: "text-xs", children: "\u2715" }) }), _jsx("h3", { className: "text-base font-medium", children: "h.AI Assistant \uC0C1\uB2F4 \uC694\uC57D" })] }) }), _jsx("div", { className: "text-xs text-gray-500 mb-2", children: "AI\uAC00 \uCC98\uB9AC\uD558\uC5EC \uC0C1\uB2F4 \uB0B4\uC6A9\uC744 \uC790\uB3D9\uD574 \uC0DD\uC131\uD569\uB2C8\uB2E4." }), _jsxs("div", { className: "mb-3", children: [_jsx("div", { className: "text-sm font-medium", children: "\uC0C1\uB2F4 \uAC1C\uC694" }), _jsx("div", { className: "text-xs text-gray-600 mt-1", children: summary ? summary.content.mainIssue : "AI가 등록 개요를 GOT 기반으로 정리했습니다. 원격 작대에 실딥 표현과 일치할 수도있으나 등 참고시 활용해 주세요." })] }), _jsxs("div", { className: "border-t border-gray-200 pt-2 mb-3", children: [_jsxs("div", { className: "flex justify-between items-center mb-1 cursor-pointer", onClick: toggleExpand, children: [_jsx("div", { className: "text-sm font-medium", children: "\uC0C1\uB2F4 \uC138\uBD80 \uC694\uC57D" }), _jsx("div", { className: "text-xs text-gray-500", children: "2023.05.07 11:03 \uAE30\uC900" })] }), expanded && (_jsx("div", { className: "text-xs text-gray-600 pl-2 border-l-2 border-gray-200 ml-1 py-1", children: summary ? (_jsxs(_Fragment, { children: ["\uBB38\uC758 \uB0B4\uC6A9: ", summary.content.mainIssue, _jsx("br", {}), "\uC0C1\uB2F4 \uACB0\uACFC: ", summary.content.result, _jsx("br", {}), "\uD6C4\uC18D \uC870\uCE58: ", summary.content.nextAction] })) : (_jsxs(_Fragment, { children: ["\uACE0\uAC1D: \uB0B4\uC6A9 \uB300\uD654 \uAE30\uB85D\uC5D0 \uC5C6\uB294 \uACF3\uC774", _jsx("br", {}), "\uC0C1\uB2F4\uC0AC: \uC81C\uD488 \uC815\uBCF4 \uC548\uB0B4\uC2DC \uC9C0\uC2DD \uC778\uAC00", _jsx("br", {}), "\uACE0\uAC1D \uAE30\uD0C0: \uBCF4\uD5D8"] })) }))] }), _jsx("button", { onClick: onSummarize, className: "w-full py-2 bg-black text-white text-sm font-medium rounded", children: "\uD604\uC7AC\uAE4C\uC9C0 \uC0C1\uB2F4\uB0B4\uC6A9 \uC694\uC57D\uD558\uAE30" })] }));
};
export default ChatSummary;
