import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const ConsultationList = ({ consultations, onSelect, selectedIndex }) => {
    return (_jsxs("div", { className: "h-full flex flex-col bg-white border-r border-gray-200", children: [_jsxs("div", { className: "p-4 border-b border-gray-200", children: [_jsx("h3", { className: "text-lg font-medium", children: "\uC0C1\uB2F4 \uBAA9\uB85D" }), _jsxs("p", { className: "text-sm text-gray-600 mt-1", children: ["\uCD1D ", consultations.length, "\uAC74"] })] }), _jsx("div", { className: "flex-1 overflow-y-auto", children: _jsx("div", { className: "space-y-1 p-2", children: consultations.map((consultation, index) => (_jsxs("div", { className: `cursor-pointer hover:bg-gray-50 p-3 rounded-lg border transition-colors ${selectedIndex === index
                            ? 'bg-blue-50 border-blue-200'
                            : 'border-gray-100'}`, onClick: () => onSelect(index), children: [_jsx("div", { className: "flex items-center justify-between mb-2", children: _jsxs("div", { className: "flex items-center", children: [_jsx("div", { className: `w-2 h-2 rounded-full mr-2 ${consultation.status === 'completed' ? 'bg-green-500' :
                                                consultation.status === 'ongoing' ? 'bg-yellow-500' : 'bg-gray-400'}` }), _jsx("p", { className: "text-sm font-medium", children: consultation.title })] }) }), _jsxs("div", { className: "text-xs text-gray-500 space-y-1", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("span", { children: [consultation.date, " ", consultation.time] }), _jsx("span", { className: `px-2 py-1 rounded text-xs ${consultation.status === 'completed' ? 'bg-green-100 text-green-700' :
                                                    consultation.status === 'ongoing' ? 'bg-yellow-100 text-yellow-700' : 'bg-gray-100 text-gray-700'}`, children: consultation.status === 'completed' ? '완료' :
                                                    consultation.status === 'ongoing' ? '진행중' : '대기' })] }), _jsx("div", { children: consultation.counselor })] })] }, consultation.id))) }) })] }));
};
export default ConsultationList;
